# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConcreteResourceVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('visited_from', models.GenericIPAddressField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_manysites.siteconcreteresourcevisit_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date and time of record creation', verbose_name='Creation Date')),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date and time of last record update', verbose_name='Update Date')),
                ('url_code', models.SlugField(max_length=255)),
                ('title', models.CharField(max_length=127)),
                ('description', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True, help_text='If you uncheck this, this resource when being accessed will raise a 404 error')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date and time of record creation', verbose_name='Creation Date')),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date and time of last record update', verbose_name='Update Date')),
                ('enabled', models.BooleanField(default=True, help_text='If you uncheck this, any resource being accessed for this site will raise a 404 error')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteConcreteResource',
            fields=[
                ('siteresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manysites.SiteResource')),
                ('content', models.TextField()),
                ('log_visits', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('manysites.siteresource',),
        ),
        migrations.CreateModel(
            name='SiteResourceAlias',
            fields=[
                ('siteresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manysites.SiteResource')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manysites.SiteConcreteResource')),
            ],
            options={
                'abstract': False,
            },
            bases=('manysites.siteresource',),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='index',
            field=models.ForeignKey(help_text='Specifying an index page will make such page accessible as the / (root) url in the related site. The page would also be accessible via its url', null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='manysites.SiteResource'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='siteresource',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_manysites.siteresource_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='siteresource',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manysites.SiteSetting'),
        ),
        migrations.AlterUniqueTogether(
            name='siteresource',
            unique_together=set([('setting', 'url_code')]),
        ),
        migrations.AddField(
            model_name='siteconcreteresourcevisit',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='manysites.SiteConcreteResource'),
        ),
    ]
