# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('manysites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SiteBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(blank=True, max_length=255)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manysites.SiteSetting')),
                ('title', models.CharField(max_length=127, null=False, blank=False)),
                ('description', models.CharField(max_length=255, null=False, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('siteasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manysites.SiteAsset')),
                ('image', models.ImageField(height_field='height', upload_to='bundle/images', width_field='width')),
                ('width', models.PositiveIntegerField(editable=False)),
                ('height', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('manysites.siteasset',),
        ),
        migrations.CreateModel(
            name='TextAsset',
            fields=[
                ('siteasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manysites.SiteAsset')),
                ('content', models.TextField(blank=True)),
                ('content_subtype', models.CharField(choices=[('plain', 'Plain'), ('javascript', 'Javascript'), ('css', 'CSS')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
            bases=('manysites.siteasset',),
        ),
        migrations.AddField(
            model_name='siteasset',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manysites.SiteBundle'),
        ),
        migrations.AddField(
            model_name='siteasset',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_manysites.siteasset_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='sitebundle',
            unique_together=set([('setting', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='siteasset',
            unique_together=set([('bundle', 'code')]),
        ),
    ]
