# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchaimage',
            name='key',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
    ]
